apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patchesStrategicMerge:
  - timelord-ingress.yaml

configMapGenerator:
  - name: timelord-config
    envs:
      - config/timelord-config.properties
  - name: ingress-config
    envs:
      - config/ingress-config.properties
    options:
      disableNameSuffixHash: true

vars:
  - name: HOST
    objref:
      kind: ConfigMap
      name: ingress-config
      apiVersion: v1
    fieldref:
      fieldpath: data.HOST
  - name: SECRET_NAME
    objref:
      kind: ConfigMap
      name: ingress-config
      apiVersion: v1
    fieldref:
      fieldpath: data.SECRET_NAME
