version: "2"
services:

  harvester:
    image: ghcr.io/reload/harvester:latest
    environment:
      VIRTUAL_HOST: harvester.docker
    ports:
      - '80'
    volumes:
      - './docker/harvester/data:/data'

  timelord:
    image: ghcr.io/reload/timelord:latest
    environment:
      VIRTUAL_HOST: timelord.docker
      # This can be pointed at harvester.reload.dk to use prod data.
      TIMELORD_HARVESTER_URL: http://harvester
      TIMELORD_SALT_STRING: ReloadGotTime
    ports:
      - '80'
    volumes:
      - '.:/var/www/html'

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - '.:/var/www/html'
