version: "2"
services:

  server:
    build:
      context: .
      dockerfile: ./docker/timelord.dockerfile
    environment:
      VIRTUAL_HOST: timelord.docker
      TIMELORD_SITE_NAME: Time Lord dev
      TIMELORD_BASE: /
      TIMELORD_HARVESTER_URL: http://harvester.reload.dk
      TIMELORD_HARVESTER_API_PATH: /api/v1/
      TIMELORD_SALT_STRING: ReloadGotTime
    ports:
      - '80'
    volumes:
      - '.:/var/www/html'

  watch:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
    volumes:
      - '.:/var/www/html'
    command: sh -c "npm install && node_modules/.bin/bower install && npm run build && npm run watch"
