version: "2"
services:

  harvester:
    image: ghcr.io/reload/harvester:latest
    environment:
      VIRTUAL_HOST: harvester.docker
    ports:
      - '80'
    volumes:
      - './docker/harvester/data/harvester.sqlite:/data/harvester.sqlite'

  timelord:
    image: ghcr.io/reload/timelord:latest
    environment:
      VIRTUAL_HOST: timelord.docker
    ports:
      - '80'
    volumes:
      - '.:/var/www/html'

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - '.:/var/www/html'
