version: "2"
services:

  harvester:
    image: harvester_server:latest
    env_file: ./docker/harvester.env
    ports:
      - 80

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./docker/timelord.env
    ports:
      - 80
    volumes:
      - '.:/var/www/html'

  watch:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
    volumes:
      - '.:/var/www/html'
    command: sh -c "npm install && node_modules/.bin/bower install && npm run build && npm run watch"
