apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-timelord
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-timelord
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-timelord
