apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelord-deployment
  labels:
    app: timelord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timelord
  template:
    metadata:
      labels:
        app: timelord
    spec:
      containers:
        - name: timelord
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
          env:
            - name: TIMELORD_SITE_NAME
              value: {{ .Values.env.timelordSiteName }}
            - name: TIMELORD_BASE
              value: {{ .Values.env.timelordBase }}
            - name: TIMELORD_HARVESTER_URL
              value: {{ .Values.env.timelordHarvestUrl }}
            - name: TIMELORD_HARVESTER_API_PATH
              value: {{ .Values.env.timelordHarvestApiPath }}
            - name: TIMELORD_SALT_STRING
              valueFrom:
                secretKeyRef:
                  name: timelord-secret
                  key: TIMELORD_SALT_STRING
