name: build-push-update

on:
  push:
    branches:
      - master
    #Ideally we want to reorganize the files/folders so they don't get copied into the image and we only trigger builds on app code changes
    paths-ignore:
      - infrastructure/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64 # Remember image in dockerfile should also support these platforms
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/timelord:latest,${{ secrets.DOCKERHUB_USERNAME }}/timelord:${{ github.sha }}
  update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
      - name: Update repo
        #Because this is a change to infrastructure kustomize manifest it is important to have the newest version so we avoid conflicts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local pull.ff only
          git pull
      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd infrastructure/base
          kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/timelord=${{ secrets.DOCKERHUB_USERNAME }}/timelord:${{ github.sha }}
          cat kustomization.yaml
      - name: Commit files
        run: |
          git commit -am "Bump docker tag: ${{ github.sha }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
